### ISSUE TITLE
Cross-compiling is broken due to upstream issue with CMakeLists.txt.

### ISSUE THREAD

**Issue by hosaka** [inexor-game/conan-grpc#11]
Just thought i'd point this out here, in case there's others who might stumble upon this issue. This was submitted ages ago to the grpc project but only recently got merged onto master: https://github.com/grpc/grpc/pull/11795

Currently, the host grpc_cpp_plugin is not being used during cross-compile, which causes steps that use protoc with grpc_cpp_plugin to fail. This can be worked around by applying the patch from the PR linked above. Hopefully this is going to be included in the next release and conan-grpc will be updated.

**Comment by Croydon** [comment]
Commit: https://github.com/grpc/grpc/commit/84189ad71aa4c3a333bfdad6427fe13be54e8892

**Comment by Croydon** [comment]
This is now part of the 1.20.0 release.

I'm not sure when I will declare a new Conan recipe version as stable, but I will create a testing/ branch for it soon

**Comment by hosaka** [comment]
Hmm, I am still getting the same error, cross-compiling on conanio/gcc8-armv8 docker image:
```
/home/conan/.conan/data/grpc/1.20.0/inexorgame/stable/build/fa8a98c91fcc12f242c23f1edad932b520a90cbe/build_subfolder/bin/grpc_cpp_plugin: program not found or is not executable
--grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
source_subfolder/CMakeFiles/grpc++_reflection.dir/build.make:63: recipe for target 'gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc' failed
make[2]: *** [gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc] Error 1
CMakeFiles/Makefile2:523: recipe for target 'source_subfolder/CMakeFiles/grpc++_reflection.dir/all' failed
make[1]: *** [source_subfolder/CMakeFiles/grpc++_reflection.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Indeed, the executable is compiled as aarch64, while it should be x86-64:
```
conan@a190a5012139:~/.conan/data$ file /home/conan/.conan/data/grpc/1.20.0/inexorgame/stable/build/fa8a98c91fcc12f242c23f1edad932b520a90cbe/build_subfolder/bin/grpc_cpp_plugin
/home/conan/.conan/data/grpc/1.20.0/inexorgame/stable/build/fa8a98c91fcc12f242c23f1edad932b520a90cbe/build_subfolder/bin/grpc_cpp_plugin: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=b57e0c5814991aa4ef67e215b6c5d61bd6d2862e, not stripped
```

**Comment by Alberto-Izquierdo** [comment]
Any update on this? I am getting the same problem

**Comment by Croydon** [comment]
Please watch #16 for progress on cross-compiling

Further progress is staled on this until both Protobuf and protoc are added in a reasonable way to CCI, see https://github.com/conan-io/conan-center-index/pull/65

**Comment by Alberto-Izquierdo** [comment]
Great, thank you so much
