### ISSUE TITLE
The recipe doesn't import protoc executable

### ISSUE THREAD

**Issue by wthwlh** [inexor-game/conan-grpc#13]
Just to point out that this grpc pack won't have protoc executable file. Which means when you want to use protoc and grpc_cpp_plugin to generate .pb file, you may have to use you ur own version of protoc (on your machine). 

This could be fixed by add an imports() in the recipe to copy "protoc" from protoc_installer pack. Or you may need to add another dependency of "protoc_installer" to manually copy bin on to your machine

**Comment by Croydon** [comment]
This grpc recipe already requires protoc_installer, so protoc should be available in the PATH 🤔

**Comment by wthwlh** [comment]
I believe when I use "conan install" to pull a dependency, conan would
cache all the libs, bins or includes under ~/.conan folder. However when I
use the recipe, I didn't find there is protoc executable available under
'bin' folder.

Croydon <notifications@github.com> 于2019年4月4日周四 下午4:02写道：

**Comment by wthwlh** [comment]
@Croydon I do know this already requires protoc_installer, but it just doesn't "bring over" that protoc file. It does have libprotoc.a though.

**Comment by Croydon** [comment]
How do you consume/use grpc after doing a `conan install grpc...`?

Are you building a project which has its own conanfile and defines as a dependency grpc? Or some other way?

**Comment by wthwlh** [comment]
@Croydon Exactly, I build a project depends on grpc and protobuf, and I pull dependencies with my own conanfile.

**Comment by wthwlh** [comment]
@Croydon It is not actually a big issue. I am just saying if using this recipe to upload your grpc package, when you may need to also install "protoc_installer" in your own conanfile

**Comment by Croydon** [comment]
That should not be necessary. What recipe version are you using? And are you sure you use the latest revision?

**Comment by wthwlh** [comment]
@wthwlh stable/1.17.2, but I use it to upload my grpc library which is 1.17.1. But that grpc_cpp_plugin executable could not find libprotoc.so (I test it in a new docker container which doesn't install protobuf at all), in which case it should be built to depends on liprotoc.a right?

**Comment by Croydon** [comment]
Closing now for good.

Importing is certainly the wrong call, if there are location problems of protoc for the newest grpc recipe available here than please open a new issue
