### ISSUE TITLE
Split into hybrid default+installer recipe

### ISSUE THREAD

**Issue by Croydon** [inexor-game/conan-grpc#16]
To fix cross-compiling issues

**Comment by KristianJerpetjon** [comment]
Just ran into this now.. temp workaround for me was 
    def configure(self):
        if self.settings.arch == "armv8":
            self.options["grpc"].build_codegen=False

however i now lack the codegen and have to run that down a different chain.. whereas i would prefer to have a 
[build_requires]
grpc_codegen

Although i have had this discussion on bincrafters before and another issue is if the codegen and the grpc needs to have the same version its very difficult to enforce it.. in a conanfile.py one could use the same version/revision in a variable to enforce consistency

**Comment by Croydon** [comment]
Not needed anymore due to new Conan cross-building model
