### ISSUE TITLE
depends on openssl though conan index has now OpenSSL

### ISSUE THREAD

**Issue by gocarlos** [inexor-game/conan-grpc#22]
it seems like on windows this package depending on openssl and other depending on OpenSSL causes issues, as the windows file system is not case sensitive.

I guess the solution here would be to upgrade the conanfile.py to use the lib with the name `OpenSSL` instead of `openssl`

```txt
...
[cmake] WARN: OpenSSL/1.0.2o@conan/stable: requirement zlib/1.2.11@conan/stable overridden by Poco/1.9.4@pocoproject/stable to zlib/1.2.11 
[cmake] 
[cmake] boost/1.69.0@conan/stable: 
[cmake] WARN: Setting 'cppstd' is deprecated in favor of 'compiler.cppstd', please update your recipe.
[cmake] 
[cmake] WARN: boost/1.69.0@conan/stable: requirement zlib/1.2.11@conan/stable overridden by your conanfile to zlib/1.2.11 
[cmake] 
[cmake] ERROR: Requested 'openssl/1.0.2t' but found case incompatible 'OpenSSL'
[cmake] Case insensitive filesystem can't manage this
....
```

**Comment by Croydon** [comment]
Actually, it is the other way around.

All recipes in the Conan Center Index (CCI) are lowercase.
Once recipes are migrated to CCI the old versions aren't maintained anymore.

Therefore `openssl/1.x.y` is here to stay. Other packages using the old references need to be updated.

Unfortunately, for Windows installations who already have the uppercase `OpenSSL` you first need to remove these packages. Conan 2.0 or another future Conan release might handle this better.

**Comment by Croydon** [comment]
Also, also: `OpenSSL/1.0.2t` does not exist. It is either `openssl/1.0.2t` or `OpenSSL/1.0.2t@conan/stable`
