### ISSUE TITLE
cmake_paths generator

### ISSUE THREAD

**Issue by dryarullin** [inexor-game/conan-grpc#28]
### Possible bug

conanfile.txt¶
```
 [requires]
 grpc/1.26.0@_/_
 
 [generators]
 cmake_paths
```

CMakeList.txt¶

```
...
include(${CMAKE_BINARY_DIR}/conan_paths.cmake)
find_package(gRPC CONFIG REQUARED)
...
// code from your test package
```

If you look in gRPCTargets.cmake:
```
set_target_properties(gRPC::grpc++_unsecure PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "wsock32;ws2_32;crypt32;libprotoc;libprotobuf;gRPC::gpr;gRPC::grpc_unsecure;gRPC::upb"
)
```

Test package the don't compile.
You can get the code where libprotobuf and libprotoc targets don't have link_directories(...).

But recipe works with cmake generator:

conanfile.txt¶
```
 [requires]
 grpc/1.26.0@_/_
 
 [generators]
 cmake
```

CMakeList.txt¶
```
...
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
find_package(gRPC CONFIG REQUARED)
...
// code from your test package
```

Because libprotobuf linked twice: 1) from protobuf, 2) from grpc. link_directories(...) use directories from protobuf target.

Thanks for the recipe!

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

https://conan.io/center/grpc
