### ISSUE TITLE
Add CMake build requirement

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [inexor-game/conan-grpc#33]
It would be nice to have CMake added as a build_requires, with the virtualenv generator. This enables usage on systems that don't have CMake pre-installed (for example CI build servers with no knowledge of CMake).

**Comment by Croydon** [comment]
We agreed in the Conan community that we don't add extremely common build_requires like CMake to the recipes

You can add build_requires to Conan profiles too

https://docs.conan.io/en/latest/reference/profiles.html

**Comment by Croydon** [comment]
And you can also add it to your own project's conanfile
