### ISSUE TITLE
gRPC is not building with cmake>3.16 and vs2019

### ISSUE THREAD

**Issue by yuriy-mochurad** [inexor-game/conan-grpc#39]
gRPC conan package can not be built anymore with following setup:

- windows 10 x64
- cmake > 3.16
- Visual Studio 2019
- conan 1.26.0

Conan profile looks like:
```
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=16
os=Windows
os_build=Windows
```

Same issue and errors reported here: https://gitlab.kitware.com/cmake/cmake/-/issues/20209

I was able to fix build locally by patching `_configure_cmake` method with:
```        
if self.settings.os == "Windows" and not self.options["protobuf"].shared:
    cmake.definitions['Protobuf_USE_STATIC_LIBS'] = "ON"
```

**Comment by Croydon** [comment]
This pretty much looks like the error I run into on my Windows machine. I will have a look somewhen later

Thanks for the info!

**Comment by bugproof** [comment]
I tested using gRPC repo (not this recipe) and it builds flawlessly with vs2019 and cmake 3.17.0 (targeting x86) . What's the problem here? Seems more like the recipe problem than gRPC itself? Is @yuriy-mochurad patch the right way to solve it?

**Comment by anton-danielsson** [comment]
I'm pretty sure this has to do with the interaction with FindProtobuf.cmake provided with CMake:
https://gitlab.kitware.com/cmake/cmake/-/blob/v3.18.4/Modules/FindProtobuf.cmake#L533
It will add "PROTOBUF_USE_DLLS" if "Protobuf_USE_STATIC_LIBS" is not set which causes incorrect linkage.

**Comment by anton-danielsson** [comment]
And it corresponds well with CMake 3.16, that logic where introduced in this commit:
https://gitlab.kitware.com/cmake/cmake/-/commit/3bbd85d5fffe66181cf16c81b23b2ba50f5387ba

**Comment by Croydon** [comment]
Thank you @anton-dirac for the additional information.

The change looks good to me on my local Windows machine. Let's see what CI says

**Comment by Croydon** [comment]
I applied the change for version 1.27.3 and it should be fixed now.

Thanks everyone!
