### ISSUE TITLE
Implement a useful test_package

### ISSUE THREAD

**Issue by Croydon** [inexor-game/conan-grpc#4]
A helpful Conan test_package...
  * should test if the build library got build correctly (no missing linked libraries etc.)
  * so it should execute some functionality to check for basic runtime errors 
  * it should NOT test ALL functionality, this is beyond the scope of a Conan test_package and should rather be part of a more classic testing system for the library
  * it should cover the points above, but should stay as minimalist as possible
  * it needs to be able to run automatically on a CI platform
   
Currently, the test_package always fails to establish a RPC connection which prints an error in the console and is therefore not very helpful to determinate if the build was truly successful.

I would like to have help from someone who is more familiar in actually using grpc and can therefore write a better test_package as I could do it myself.

The current test_package can be found here: https://github.com/inexorgame/conan-grpc/tree/stable/1.17.2/test_package

To build grpc execute:
`conan create . inexorgame/stable`

To just run the test_package as there is no need to build it everytime:
`conan test test_package grpc/1.17.2@inexorgame/stable`

Help would be really appreciated, thanks!

**Comment by rdewaele** [comment]
GRPC Has some small examples / projects which could be used for this purpose, for example:

https://grpc.io/docs/tutorials/basic/c.html#example-code-and-setup

It creates a server and a client, and does some communication. If you consider this to be a good option, I could make a PR for this ... someday. It would have to happen in my free time which is scarce for the foreseeable future. ;-)

**Comment by Croydon** [comment]
I would prefer more the hello_world example as it has CMake support, which makes cross-platform easier https://github.com/grpc/grpc/tree/v1.17.1/examples/cpp/helloworld

This is also what the current test_package partially uses (just client).

The main problem is that we would need to run two executables at the same time (client & server), we would need to wait for them to finish the hello world example and then kill both processes reliable and this all in cross-platform manner.

**Comment by rdewaele** [comment]
Shouldn't it be possible to have a single executable with a client and a server thread?

**Comment by Croydon** [comment]
Done via  #24
