### ISSUE TITLE
grpc v.1.34.1 has been released

### ISSUE THREAD

**Issue by winternet** [inexor-game/conan-grpc#48]
A new version of grpc has been released recently (see: https://github.com/grpc/grpc/releases/tag/v1.34.1).

conandata.yaml could be extended as follows after creating a new branch:

```
+  "1.34.1":
+    url: https://github.com/grpc/grpc/archive/v1.34.1.zip
+    sha256: 0884778ef7866c2aaa9c06abd820f2ba2b514edcc5ec21bda74f3b7253036f9d
```

**Comment by Croydon** [comment]
Done via https://github.com/inexorgame/conan-grpc/commit/ae7fa8e99a8d5c2ed7270c659a34911df0ca488a
