### ISSUE TITLE
cpp_info.libs and SSL/TLS

### ISSUE THREAD

**Issue by mys007** [inexor-game/conan-grpc#49]
There is a problem in this conan package recipe when using grpc for encrypted communication (SSL/TLS). The support silently fails if one does not link with the correct libraries (see https://github.com/grpc/grpc/issues/24918). Since the recipe here is compiled with the support for encryption, it should not link with `grpc++_unsecure.lib`, `grpc_unsecure.lib`, `grpc_cronet.lib`: these should be removed from `self.cpp_info.libs` in `conanfile.py`.

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

https://conan.io/center/grpc
