### ISSUE TITLE
Fix x86 builds of Clang 3.9, Clang 4 and Clang 5

### ISSUE THREAD

**Issue by Croydon** [inexor-game/conan-grpc#5]
See failing logs in the current default branch on Travis.

E.g. https://travis-ci.org/inexorgame/conan-grpc/builds/475561210

Contributions or tips highly appreciated! 😄

**Comment by rdewaele** [comment]
Looking at
https://travis-ci.org/inexorgame/conan-grpc/jobs/475561221

and the first error (unless I missed something, it's a long log):

```
[ 47%] Building CXX object source_subfolder/CMakeFiles/grpc_unsecure.dir/src/core/ext/filters/message_size/message_size_filter.cc.o
/home/conan/.conan/data/protobuf/3.6.1/bincrafters/stable/package/3072537f11e3374ae5ab90223ffced9365f58990/lib/libprotobuf.a(arena.cc.o): In function `google::protobuf::internal::ArenaImpl::Init()':
/home/conan/.conan/data/protobuf/3.6.1/bincrafters/stable/build/3072537f11e3374ae5ab90223ffced9365f58990/source_subfolder/src/google/protobuf/arena.cc:(.text+0x35): undefined reference to `__atomic_fetch_add_8'
```

Could it be that -latomic is missing? I'm not sure how to reproduce travis builds, but you mentioned that tips are also welcome. 😄 

See for example: https://stackoverflow.com/questions/31381892/fedora-22-compile-atomic-is-lock-free

**Comment by uilianries** [comment]
It's weird because Protobuf adds libatomic for clang x86:

https://github.com/bincrafters/conan-protobuf/blob/stable/3.6.1/conanfile.py#L83

**Comment by Croydon** [comment]
Also it should likely be there for all (Clang) builds are be missing for all (Clang) builds, right? 🤔

**Comment by uilianries** [comment]
Yes, all clang versions (3.9, ..., 7.0), but only for x86.

**Comment by rdewaele** [comment]
I have had some issues with linker argument positioning in the past, because lookups are from left to right in the library list. Maybe that's related?
If someone could point me to / provide some guidelines on how to reproduce these builds I'm willing to play around with them.

**Comment by uilianries** [comment]
Yes, it could be related. Unfortunately, Conan is not smart enough to deduce the correct library order list, so we need to be explicit in cpp_info.libs

**Comment by rdewaele** [comment]
An alternative approach could maybe be to use the -Wl, --start-group --end-group flags?

**Comment by uilianries** [comment]
No, --start-group are not supported by Conan. I just tried to use with Abseil, but it's a total mess, because I can't wrap the library list. I'm investigating to find a correct fix.

**Comment by uilianries** [comment]
@Croydon The problem is that gRPC is using an internal protobuf.cmake file, which doesn't list libatomic and of course, ignores conan libs.

There are few options:
- Patch gRPC/CMakeLists.txt to use conan protobuf libs:
```python
tools.replace_in_file(os.path.join(self._source_subfolder, "CMakeLists.txt"), "_gRPC_PROTOBUF_LIBRARIES", "CONAN_LIBS_PROTOBUF")
```
- Patch gRPC/cmake/protobuf.cmake to use `${CONAN_LIBS_PROTOBUF}` instead of forcing libprotobuf only
- Replace protobuf.cmake by `find_package(protobuf)` and set all expected definitions

The first option worked for me, I'm using conanio/clang50-x86 to reproduce your error.

**Comment by Croydon** [comment]
Option 1 seems to work. Thank you so much for investigating this! 

https://github.com/inexorgame/conan-grpc/commit/39da3b5c001ee026578a7087c55c1ee7500205f2

What I'm wondering however, if atomic only makes problems on  x86 on Clang 3.9, 4 and 5 why do we add it for all Clang versions in Protobuf? Is this necessary?

**Comment by uilianries** [comment]
According the [documentation](https://releases.llvm.org/5.0.0/tools/clang/docs/Toolchain.html#id16):

> Clang does not currently automatically link against libatomic when using libgcc_s. You may need to manually add -latomic to support this configuration when using non-native atomic operations 

Thus when cross-building to x86 we need to add `-libatomic`. However, LLVM docs use the same note for Clang 6, 7 and 8, which puzzles me because it only happens with previous versions. :thinking:

**Comment by Croydon** [comment]
Hm, alright. We can review this workaround somewhen in the future again.

This issue seems to be done for now.

Thanks again!
