### ISSUE TITLE
Error in basic setup command

### ISSUE THREAD

**Issue by Vipin-Sharma** [inexor-game/conan-grpc#57]
Getting error while running the basic setup command

command: conan install grpc/1.34.1@inexorgame/stable

Console output:

Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

grpc/1.34.1@inexorgame/stable: Not found in local cache, looking in remotes...
grpc/1.34.1@inexorgame/stable: Trying with 'bintray'...
grpc/1.34.1@inexorgame/stable: Trying with 'conan-center'...
grpc/1.34.1@inexorgame/stable: Trying with 'bincrafters'...
ERROR: Unable to find 'grpc/1.34.1@inexorgame/stable' in remotes

Kernel version: 5.8.0-50-generic

**Comment by vhavel** [comment]
Probably because Bintray repositories have been deprecated today
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by Croydon** [comment]
This recipe is now in the [Conan Center Index](https://github.com/conan-io/conan-center-index/).

Please migrate to the recipe version there. 
If this is still an issue, please create a new issue in the [Conan Center Index issue tracker](https://github.com/conan-io/conan-center-index/issues).

Thanks!

https://conan.io/center/grpc

**Comment by Croydon** [comment]
The old grpc recipes will are available for the time being via this Conan repository: https://bincrafters.jfrog.io/artifactory/api/conan/conan-legacy-inexorgame
