### ISSUE TITLE
Figure out if we can update to newer OpenSSL versions

### ISSUE THREAD

**Issue by Croydon** [inexor-game/conan-grpc#6]
I tested this in the past, but it wasn't possible.

The Conan recipe currently uses 1.0.2. 
Can we update to 1.1.0 or even 1.1.1 now?

**Comment by rdewaele** [comment]
What was the exact issue in the past that prevented updating OpenSSL?

I just ran a build in ubuntu with an updated OpenSSL dependency (1.1.1a) and it compiled just fine, which tells me that there is most likely more to this issue. If there isn't, I can make a PR and see what the CI has to say about it. ;-)

**Comment by Croydon** [comment]
> What was the exact issue in the past that prevented updating OpenSSL?

This is a very fair question. To be honest I don't remember personally, and back then we hadn't CI enabled in this repository, so it might be buried somewhere in the logs of Inexor's Main CI 🙈 

I know, however, that starting with I believe version 1.1.0 I have tried to use more modern OpenSSL versions with every new version again and again and eventually gave up on it. At one time I also uploaded it as a branch: https://github.com/inexorgame/conan-grpc/commits/testing/1.8.3-openssl-1.1.0

Anyway, the versions between 1.14.1 and 1.17.2 were broken in likely more than one way, that's why I haven't promoted any version between these two as stable. And versions before 1.14.1 and 1.14.1 itself might just not be prepared for newer OpenSSL versions.

Let's see what CI is saying, maybe it is working now.

**Comment by Croydon** [comment]
Seems like Linux and macOS are fine with OpenSSL 1.1.1a (except some Clang builds which is issue #5)

https://travis-ci.org/inexorgame/conan-grpc/builds/476169017

But Window is failing completely:

https://ci.appveyor.com/project/inexorgame/conan-grpc-xr8rf/builds/21424908

**Comment by SSE4** [comment]
I suppose Windows builds need to link against `crypt32.lib` (for [CertOpenStore ](https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-certopenstore) and friends).
OpenSSL's `package_info` method declares it https://github.com/conan-community/conan-openssl/blob/release/1.1.1a/conanfile.py#L337, so it's weird why library isn't linked

**Comment by Croydon** [comment]
I just tried again with grpc 1.20.0 + OpenSSL 1.1.1b and it runs now in another error

https://ci.appveyor.com/project/inexorgame/conan-grpc-xr8rf

I will have a second look later

**Comment by uilianries** [comment]
I'm curious if you can use OpenSSL 1.1.0 with gRPC. I found 1.0.2 in code base:

https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/tools/openssl/use_openssl.sh#L24

**Comment by Croydon** [comment]
grpc might use per default 1.0.2 but many issues and discussion strongly imply that newer OpenSSL versions are supported as well.

Linux/macOS do succeed in building now https://travis-ci.org/inexorgame/conan-grpc/builds/521598915

Windows is failing as it can't found Cert symbols which should be part of the CAPI engine in OpenSSL. While this option isn't explicit handled in the OpenSSL recipe, the engine should be build by default on system which gets supported by this engine.

https://ci.appveyor.com/project/inexorgame/conan-grpc-xr8rf/build/job/7abg8tk5xhu4uraf#L1533

I have edited the OpenSSL recipe locally to handle the `no_capieng` explicit, but no change in the result. Maybe linking needs adopting in some way 🤔 

https://github.com/openssl/openssl/blame/822e6d95e063a8fb6cd6b8e272dc5d9338c72601/INSTALL#L290

**Comment by Croydon** [comment]
@SSE4 a `libapps.lib` is getting built which doesn't seem to get handled by the `package_info()` in OpenSSL, not sure if this is connected

**Comment by Croydon** [comment]
@SSE4 This might be related to https://github.com/conan-community/community/issues/14 

It seems like https://github.com/conan-community/conan-openssl/pull/80/commits/fbb3aba93a9bd78b19aec4dcb8c482a5d6315697 just got merged in one version branch, not 1.1.0 and 1.1.1

**Comment by Croydon** [comment]
But I'm not sure if path/names are still the same 🤔

**Comment by SSE4** [comment]
OpenSSL has many branches and I usually back-port only by request. do you need with fix in 1.1.1b or some another branch?

**Comment by Croydon** [comment]
In that case it would be a forward porting, not back porting :)

But let my first test that later on first, there is still something about the `capieng` engine I'm not really getting, and files/paths may have changed between the releases

**Comment by SSE4** [comment]
okay, feel free to open PRs to OpenSSL 1.1.1b or 1.1.0b for the forward porting

**Comment by Croydon** [comment]
But since it is in `1.0.2p` it should be at least in `1.0.2r`

**Comment by SSE4** [comment]
yeah, but `1.0.2r` is an old version, I'd prefer to use latest if possible (`1.1.1b`), especially for security-critical libraries like OpenSSL

**Comment by Croydon** [comment]
True, but 1.0.2 is still maintained and not all consumers support newer versions

**Comment by Croydon** [comment]
See https://github.com/grpc/grpc/issues/21293
