### ISSUE TITLE
Any plan for ios & android

### ISSUE THREAD

**Issue by forvenus** [inexor-game/conan-grpc#8]
Hi Croydon,

Thanks for the Great job! I've tried grpc on Macos and it can work well.

However, I see the mobile related code is commented out currently as below, so I'd like to ask if there's any plan to get the cross-comiple done?

`# This doesn't work yet as one would expect, because the install target builds everything
        # and we need the install target because of the generated CMake files
        #
        #   enable_mobile=False # Enables iOS and Android support`

**Comment by Croydon** [comment]
I would happily accept contributions to get Android & iOS done.

Personally, however, I will only work on Linux/Windows/macOS for the foreseeable future.

**Comment by forvenus** [comment]
Got it, thanks for quick response:-)

**Comment by sssilver** [comment]
We would also love to see this happen. What would that entail?

Also while mobile support is lacking, this ticket should probably stay open.
